version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: diegourban/nginx
    container_name: nginx
    networks:
      - production-network
    ports:
      - "80:80"
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    networks:
      - production-network

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: diegourban/alura-books
    container_name: alura-books-1
    networks:
      - production-network
    ports:
      - "3000"
    depends_on:
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: diegourban/alura-books
    container_name: alura-books-2
    networks:
      - production-network
    ports:
      - "3000"
    depends_on:
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: diegourban/alura-books
    container_name: alura-books-3
    networks:
      - production-network
    ports:
      - "3000"
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge
